### ISSUE TITLE
OSErrror

### ISSUE THREAD

**Issue by Re-dot-art** [TonyLianLong/UnsupervisedSelectiveLabeling#4]
when I run the command:    cd selective_labeling    **python usl-cifar.py**     An error has occurred here. May I ask how to solve it?
![image](https://user-images.githubusercontent.com/93500522/235285724-feda0849-c2ab-4403-9d7b-39c1c2df0b6b.png)

**Comment by TonyLianLong** [comment]
This is a pyKeops error. Please check your installation https://www.kernel-operations.io/keops/python/installation.html .
