### ISSUE TITLE
Bug for Evaluate USL-T on CIFAR-10 on SimCLR-CLD

### ISSUE THREAD

**Issue by grilled-chicken-burger** [TonyLianLong/UnsupervisedSelectiveLabeling#6]
Dear author,
         When i execute the python fine_tune.py --cfg configs/cifar10_usl-t_finetune.yaml, i got the error FileNotFoundError: [Errno 2] No such file or directory: '../pretrained/cifar10_ckpt_epoch_200.pth'。Could you help solve this problem? Thank you!

**Comment by TonyLianLong** [comment]
You need a trained ckpt in order to fine-tune. See README to download cifar10_ckpt_epoch_200.pth.
